CREATE TABLE webhook_registrations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id      VARCHAR(64) NOT NULL,
    route_path        VARCHAR(256) NOT NULL,
    event_type        VARCHAR(64),
    webhook_token_enc CLOB NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_webhook_registrations_workspace_path UNIQUE (workspace_id, route_path),
    CONSTRAINT fk_webhook_registrations_workspace FOREIGN KEY (workspace_id) REFERENCES installations(workspace_id) ON DELETE CASCADE
);
CREATE INDEX idx_webhook_registrations_workspace ON webhook_registrations(workspace_id);
